# SPDX-FileCopyrightText: © 2022 Matt Williams <matt@milliams.com>
# SPDX-License-Identifier: MIT

name: CI

on: [push, pull_request]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: pip install poetry
      - name: Setup package
        run: poetry install
      - name: Generate the GeoJSON
        run: poetry run generate
  deploy:
    runs-on: ubuntu-latest
    needs: [generate]
    if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: pip install poetry
      - name: Setup package
        run: poetry install
      - name: Generate the GeoJSON
        run: poetry run generate
      - name: Move everything into place
        run: |
          mkdir build
          cp groups.json build
          cp rse-groups.js build
          cp index.html build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
